### ISSUE TITLE
Stopped working in Chrome.

### ISSUE THREAD

**Issue by hluup** [madrobby/dom-monster#16]
Dom Monster stopped working in Google Chrome (8.0.552.237). When clicking on the bookmark or on the link at homepage I get the following error in javascript console:

**Uncaught SyntaxError: Unexpected token (**

at dommonster.js:1

Ps. It's still working both in IE and Firefox.

**Comment by madrobby** [comment]
Work fine here (Chrome 8.0.552.237 on Mac OS X 10.6.6). Caching problem, maybe?

**Comment by hluup** [comment]
Seems so, emptied my cache (which I should have done at first!) and all is fine again.

My bad.
