### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by johannburkard** [madrobby/dom-monster#21]
Got this error at [media.io](http://media.io).

Error [Exception... "Security error" code: "1000" nsresult: "0x805303e8 (NS_ERROR_DOM_SECURITY_ERR)" location: "http://mir.aculo.us/dom-monster/dommonster.js?14991 Line: 252"] while analyzing page. Please let the DOM Monster know about this problem!

:-)

**Comment by madrobby** [comment]
should be fixed in v1.2.3.
