### ISSUE TITLE
Error TypeError: Cannot read property 'length' of null while analyzing page.

### ISSUE THREAD

**Issue by spiderswebz** [madrobby/dom-monster#22]
Whilst checking the latest version (1.2.2) I encountered the above error applying it to a page that happened to be open, the mcurtis fork of DOMmonster.

(URI: http://github.com/mcurtis/dom-monster)

I am submitting this ticket as per the message shown next to the error.

For complete clarity I have added a screenshot [here](http://innovaweb.co.uk/media/mccurtis_dommonster_github_dm122.png)

**Comment by madrobby** [comment]
should be fixed in v1.2.3, at least i can't reproduce. :)

**Comment by spiderswebz** [comment]
That was quick - yo' da man!
