### ISSUE TITLE
Nesting depth rule conflicts with inline style rule

### ISSUE THREAD

**Issue by dave1010** [madrobby/dom-monster#27]
The rule:

> Nesting depth is very high. Some of the nodes are nested more than 15 levels deep (these are marked with a dashed red border).

adds `style="border: 1px dashed rgb(255, 0, 0);"` to deep DOM nodes. These are then picked up by the rule:

> Reduce the number of tags that use the style attribute, replacing it with external CSS definitions

Could either the order of the rules be changed, or could any rules that add a style change to adding class instead?

Browser: Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.9.2.13) Gecko/20101206 Ubuntu/10.10 (maverick) Firefox/3.6.13

**Comment by dave1010** [comment]
This rule also adds a `style="..."`:

> Some nodes use transparency. To improve rendering performance, try not to use the CSS opacity property (found ... nodes, marked with a dashed blue border).

**Comment by madrobby** [comment]
Well spotted! Can you patch and submit a pull request that just changes the order so we don't run into this?

Alternatively, all affected nodes could be added to an array, and augmented only after all the tests have been run (cleaner solution!).

**Comment by dave1010** [comment]
Pull request: https://github.com/madrobby/dom-monster/pull/28 (hope I've done it right)

**Comment by madrobby** [comment]
Merge pull request #28 from dave1010/dom-monster

---

Closed by 5d638953b7db6ee787442cce8d9e1f60ffee88d3: Nesting depth rule conflicts with inline style rule.

This seems to work better now.

(This is my first pull request on GitHub, so go easy!)
