### ISSUE TITLE
Multiple clicks on bookmarklet pollute dom stats

### ISSUE THREAD

**Issue by cppforlife** [madrobby/dom-monster#3]
To reproduce: 
1. Click once on bookmarklet and remember the results. 
2. Close overlay. 
3. Click bookmarklet again and see that dom stats changed (e.g. +2 scrpt tags...)

I didnt look at the code but I imagine that it should be pretty easy to clean up some if not all changes that bookmarklet makes to dom.

**Comment by FabianBeiner** [comment]
I can't reproduce this. Actually, the script-counting-part checks for "dommonster.js" as script source (and doesn't count it).

**Comment by cebjyre** [comment]
I'm reproducing it on this very page - the specific script tags warning isn't changing, but the number of elements, nodes, serialized DOM size etc is increasing

**Comment by FabianBeiner** [comment]
Yes, you're right. I just had a look on the example (script tags), which still don't appear. But indeed, it keeps the old div and script tag in the dom.
