### ISSUE TITLE
DomMonster plugin interface

### ISSUE THREAD

**Issue by fbuchinger** [madrobby/dom-monster#30]
Hi Thomas,

unfortunately I missed your Dom Monster! presentation yesterday at the jsvienna meeting. So I'm sending my feedback via github: DomMonster is a really neat idea! Do you plan to extend it with a plugin interface? If e.g. jQuery is detected on the page, dom monster could lazy-load a jquery specific introspection plugin.

This module could analyze jQuery.cache and state the number of jQuery event handlers assigned or the total amount of bytes stored in jquery.data. It could warn the user if too many direct event handlers were assigned and e.g. recommend the use of jQuery.delegate.

Or it could detect the most popular jQuery plugins and check if the most recent version was used.

**Comment by madrobby** [comment]
Indeed that would be cool. I think that's something for a V2, and the code is in dire need of refactoring anyway. I hope to get around to rewrite it from the ground up one of these days...
