### ISSUE TITLE
mir.aculo.us?

### ISSUE THREAD

**Issue by Draino** [madrobby/dom-monster#32]
Location: http://www.betsybermuda.com/
User agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-GB; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13 GTB7.1
{anonymous}()@http://mir.aculo.us/dom-monster/dommonster.js?15006:11
{anonymous}()@http://mir.aculo.us/dom-monster/dommonster.js?15006:11
{anonymous}(13)@http://mir.aculo.us/dom-monster/dommonster.js?15006:11

**Comment by madrobby** [comment]
Add check if console exists, closed by 9eb1861fa08ee9f6ebba09493e0b491cb851a1e7
