### ISSUE TITLE
Broken in IE 8

### ISSUE THREAD

**Issue by davija** [madrobby/dom-monster#41]
When using in IE 8, this goes boom.  

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C)
Timestamp: Wed, 16 Mar 2011 16:51:58 UTC

Message: JScript object expected
Line: 11
Char: 827
Code: 0
URI: http://mir.aculo.us/dom-monster/dommonster.js?15049

Message: JScript object expected
Line: 11
Char: 827
Code: 0
URI: http://mir.aculo.us/dom-monster/dommonster.js?15049

**Comment by davija** [comment]
http://stackoverflow.com/questions/2735067/how-to-convert-a-dom-node-list-to-an-array-in-javascript

**Comment by davija** [comment]
Issue 42 addresses a patch to fix this

**Comment by dmikey** [comment]
I've got some code also to fix jDrop, and other items. See my fork.
