### ISSUE TITLE
DOM-Size Calculation triggering too late

### ISSUE THREAD

**Issue by mRs-** [madrobby/dom-monster#45]
Hey, i found out that the DOM-Size Calculation is triggering too late.

When i trigger
document.body.innerHTML.length/1024*100/100 on my Page the result is 100K

now i am using the DOM-Monster and the DOM-Size is growing (for the Javascript and Calculating and of course for the inline styles which mark the red and blue boxes in the page) like hell + 180% (now i have 280K on my page).

So trigger the Calculation before modifying the DOM.

**Comment by madrobby** [comment]
Not good! Do you think you can find the issue and patch it?

**Comment by mRs-** [comment]
absolute, i am patching it asap.

**Comment by mRs-** [comment]
But in the fact of wrong Numbers we need to change the values for red, orange and green badge on the output value or?

**Comment by madrobby** [comment]
basically, the dom monster must always exclude itself when measuring. that should solve all problems. :)

**Comment by mRs-** [comment]
Here is the Patch for the DOM-Size worked fine for me.

<pre>
diff --git a/src/dommonster.js b/src/dommonster.js
index fb28653..8ff4d69 100644
--- a/src/dommonster.js
+++ b/src/dommonster.js
@@ -693,7 +693,7 @@
   };
 
   JR.performanceTips = function(){
→    JR.cssTips();
→    var domsize = document.body.innerHTML.length;
 
     function level(value,mid,high){
       return value&lt;mid?'low':value&lt;high?'mid':'high';
@@ -713,7 +713,7 @@
       }
     }
     average = average/nodes.length;
→    var domsize = document.body.innerHTML.length;
+    
     JR.stats(nodes.length, 'elements', level(nodes.length,750,1500));
 
     JR.nodesTips();
@@ -740,6 +740,7 @@
     if(very)
       JR.warn('Nesting depth is very high.','Some of the nodes are nested more than 15 levels deep (these are marked with a dashed red border).');
 
→    JR.cssTips();
     JR.doctypeTips();
     JR.frameworkTips();
     JR.webfontTips();
</pre>


how can i add this as a Patch here? (sorry i am new to GIT)

**Comment by madrobby** [comment]
http://help.github.com/pull-requests/ — we're doing fork+pull.
