### ISSUE TITLE
Prototype version

### ISSUE THREAD

**Issue by victor-homyakov** [madrobby/dom-monster#48]
I receive such message from DOM Monster 1.3.1:
You are using the Prototype JavaScript framework v1.7. There's a newer version available, which potentially includes performance updates.

Is this a bug or not?

**Comment by victor-homyakov** [comment]
Results from Chrome console:

```
> JR.versionCompare("1.7", [1, 7])
true
> JR.versionCompare("1.7.1", [1, 7, 1])
true
> JR.versionCompare("1.7", [1, 7, 1])
true
> JR.versionCompare("1.6", [1, 7])
false
> JR.versionCompare("1.6.0.3", [1, 7])
false
```

Either invert result of JR.versionCompare (true instead of false) or use `if('Prototype' in window && !JR.versionCompare(...`. Also `JR.versionCompare("1.7", [1, 7, 1])` should return false.

**Comment by mRs-** [comment]
seems like you figured this already out. Make a Fork and a Pull Request please
