### ISSUE TITLE
if if vs if else (please write performant JS -))

### ISSUE THREAD

**Issue by ainthek** [madrobby/dom-monster#8]
if (element.nodeType == 8) comments++;
            if (element.nodeType == 3 && /^\s+$/.test(element.nodeValue)) {
                // if(JR._firebug) console.warn('Whitespace-only text node', element);
                whitespace++;
            }
            if (element.nodeType == 3) textnodes++;

**Comment by madrobby** [comment]
You're welcome to submit pull requests/patches. However, I think DOM Monster will grow and change quite a bit so premature micro-optimizations might be a might early...
